apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    app: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: udagram-api-user
          image: samdana12/udagram-api-user:v1
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
            limits:
              cpu: "500m"              
          env:
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRES_HOST
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: JWT_SECRET                  
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_SESSION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_SESSION_TOKEN                                                      
            - name: AWS_PROFILE
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: AWS_PROFILE
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: AWS_REGION
            - name: AWS_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: AWS_BUCKET