apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: udagram-frontend
          image: samdana12/udagram-frontend:v6
          imagePullPolicy: "Always"
          ports:
            - containerPort: 80 
          resources:
            requests:
              cpu: "250m"
            limits:
              cpu: "500m"                     